fixes #7 #9 #11 added ElementsBy, AnyN, and Less
arr-ai/frozen pull request #14
Opened 2020-01-10 00:39 UTC by nofun97

Fixes #7 #9 #11 

Added `ElementsBy`, `AnyN` and `Less` data structure

2020-01-10 03:04 UTC, marcelocantos requested changes

2020-01-10 03:04 UTC, marcelocantos commented on set.go
> +// AnyN returns a set N arbitrary element from the Set
`... set of ... elements ...`.
`s/$/./`

2020-01-10 03:04 UTC, marcelocantos commented on set.go
> +// Takes elements in a defined order
`s/$/./`

2020-01-10 03:04 UTC, marcelocantos commented on set.go
> +		if n == 0 {
Test not required. It's valid to ask for more elements than the set has.

2020-01-10 03:04 UTC, marcelocantos commented on set.go
> +	setBuilder := NewSetBuilder(0)
```go
var setBuilder SetBuilder
```

2020-01-10 03:04 UTC, marcelocantos commented on node_iter.go
> +// Less dictates the order of two elements
`s/$/./`

2020-01-10 03:04 UTC, marcelocantos commented on set_test.go
> +	assert.Equal(t, []interface{}{5, 4, 3, 2, 1}, s.ElementsBy(less))
Try a much larger input. Use `Iota`.

2020-01-10 03:04 UTC, marcelocantos commented on set_test.go
> +	assert.True(t, s.AnyN(2).Equal(NewSet(1, 2)))
Try much larger values of N.

2020-01-11 01:27 UTC, nofun97 commented on set.go
> +// Takes elements in a defined order
sorry what does `s/$/./` mean?

2020-01-12 02:15 UTC, nofun97 commented on set_test.go
> +	assert.True(t, s.AnyN(2).Equal(NewSet(1, 2)))
added

2020-01-12 02:15 UTC, nofun97 commented on set_test.go
> +	assert.Equal(t, []interface{}{5, 4, 3, 2, 1}, s.ElementsBy(less))
changes added

2020-01-12 02:15 UTC, nofun97 commented on set.go
> +	setBuilder := NewSetBuilder(0)
changed to that

2020-01-12 02:15 UTC, nofun97 commented on set.go
> +		if n == 0 {
removed the test

2020-01-13 00:49 UTC, nofun97 commented on set.go
> +// AnyN returns a set N arbitrary element from the Set
added

2020-01-13 00:49 UTC, nofun97 commented on set.go
> +// Takes elements in a defined order
added

2020-01-13 00:49 UTC, nofun97 commented on node_iter.go
> +// Less dictates the order of two elements
added

2020-01-13 00:57 UTC, ChloePlanet commented on set_test.go
> +	less := func(a, b interface{}) bool { return a.(int) < b.(int) }
less := Less...

2020-01-13 00:57 UTC, ChloePlanet commented on node_iter.go
> +type Less func(a, b interface{}) bool
L55: replace `func(a, b interface{}) bool` with `Less`

2020-01-13 02:48 UTC, ChloePlanet approved these changes

2020-01-13 02:52 UTC, merged